# Generated by Django 3.0.7 on 2020-07-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=10)),
                ('categories', models.CharField(choices=[('waf', 'WASH AND FOLD'), ('wai', 'WASH AND IRON'), ('ironing', 'IRONING'), ('dc', 'DRY CLEANING'), ('wfi', 'WASH FOLD AND IRONING')], default='waf', max_length=21)),
                ('time_slot', models.CharField(choices=[('plz', 'PLEASE SELECT A TIME SLOT'), ('9t10', '9AM-10AM'), ('10t11', '10AM-11AM'), ('11t12', '11AM-12PM'), ('12t1', '12PM-1PM'), ('1t2', '1PM-2PM'), ('2t3', '2PM-3PM'), ('3t4', '3PM-4PM'), ('4t5', '4PM-5PM'), ('5t6', '5PM-6PM'), ('6t7', '6PM-7PM'), ('7t8', '7PM-8PM'), ('8t9', '8PM-9PM')], default='plz', max_length=23)),
                ('order_date', models.DateField(null='true')),
            ],
        ),
    ]
