# Generated by Django 3.0.7 on 2020-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0004_auto_20200907_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
